### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hampsterx** [summerwind/secretctl#1]
nice project for lightweight solution. Getting go panic however :(

```
 secretctl push --vault-token my-token

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7670cb]

goroutine 1 [running]:
github.com/summerwind/secretctl/cmd.bindFlags(0xc4200a62d0, 0xc42012c8a0, 0xc42012c8a0, 0x0)
	/home/travis/gopath/src/github.com/summerwind/secretctl/cmd/util.go:14 +0x2b
github.com/summerwind/secretctl/cmd.runPushCommand(0xc4200c9200, 0xc42012c860, 0x0, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/summerwind/secretctl/cmd/push.go:36 +0xdc
github.com/summerwind/secretctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200c9200, 0xc42012c700, 0x2, 0x2, 0xc4200c9200, 0xc42012c700)
	/home/travis/gopath/src/github.com/summerwind/secretctl/vendor/github.com/spf13/cobra/command.go:632 +0x3ef
github.com/summerwind/secretctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200c8fc0, 0xc420053f58, 0x1, 0xc4200c9680)
	/home/travis/gopath/src/github.com/summerwind/secretctl/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/summerwind/secretctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200c8fc0, 0xc420053f50, 0x1)
	/home/travis/gopath/src/github.com/summerwind/secretctl/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/travis/gopath/src/github.com/summerwind/secretctl/secretctl.go:48 +0x790
```

.secret.yaml

```
files:
  config/test:
    vault:
      path: secrets/test
```

**Comment by hampsterx** [comment]
my bad. requires storage.vault which I missed from config

```
storage:
  vault:
    addr: https://127.0.0.1:8200
```
